export interface SpotlessArea {
  slug: string
  city: string
  state: string
  stateAbbr: string
  county: string
  zipCodes: string[]
  neighborhoods: string[]
  landmarks: string[]
  lat: number
  lng: number
}

export const SPOTLESS_AREAS: SpotlessArea[] = [
  {
    slug: "los-angeles",
    city: "Los Angeles",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["90001", "90012", "90015", "90017", "90026", "90027", "90028", "90029", "90036", "90038"],
    neighborhoods: ["Downtown LA", "Hollywood", "Silver Lake", "Echo Park", "Koreatown", "Los Feliz"],
    landmarks: ["Hollywood Sign", "Griffith Observatory", "The Grove", "LA Live"],
    lat: 34.0522,
    lng: -118.2437,
  },
  {
    slug: "santa-monica",
    city: "Santa Monica",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["90401", "90402", "90403", "90404", "90405"],
    neighborhoods: ["Ocean Park", "Montana Avenue", "Main Street", "Wilshire Montana"],
    landmarks: ["Santa Monica Pier", "Third Street Promenade", "Palisades Park"],
    lat: 34.0195,
    lng: -118.4912,
  },
  {
    slug: "beverly-hills",
    city: "Beverly Hills",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["90210", "90211", "90212"],
    neighborhoods: ["The Flats", "Trousdale Estates", "Beverly Hills Gateway", "South Beverly Hills"],
    landmarks: ["Rodeo Drive", "Beverly Wilshire Hotel", "Greystone Mansion"],
    lat: 34.0736,
    lng: -118.4004,
  },
  {
    slug: "west-hollywood",
    city: "West Hollywood",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["90046", "90048", "90069"],
    neighborhoods: ["Sunset Strip", "West Hollywood West", "Norma Triangle", "Beverly Grove"],
    landmarks: ["Sunset Strip", "Pacific Design Center", "The Abbey"],
    lat: 34.0900,
    lng: -118.3617,
  },
  {
    slug: "burbank",
    city: "Burbank",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["91501", "91502", "91504", "91505", "91506"],
    neighborhoods: ["Media District", "Magnolia Park", "Rancho Equestrian", "Hillside"],
    landmarks: ["Warner Bros Studio", "Disney Studios", "Burbank Town Center"],
    lat: 34.1808,
    lng: -118.3090,
  },
  {
    slug: "glendale",
    city: "Glendale",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["91201", "91202", "91203", "91204", "91205", "91206", "91208"],
    neighborhoods: ["Downtown Glendale", "Adams Hill", "Rossmoyne", "Sparr Heights", "Verdugo Woodlands"],
    landmarks: ["The Americana at Brand", "Glendale Galleria", "Forest Lawn Memorial Park"],
    lat: 34.1425,
    lng: -118.2551,
  },
  {
    slug: "pasadena",
    city: "Pasadena",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["91101", "91103", "91104", "91105", "91106", "91107"],
    neighborhoods: ["Old Town", "South Lake", "Bungalow Heaven", "Madison Heights", "Caltech area"],
    landmarks: ["Rose Bowl", "Norton Simon Museum", "Old Town Pasadena", "Caltech"],
    lat: 34.1478,
    lng: -118.1445,
  },
  {
    slug: "long-beach",
    city: "Long Beach",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["90801", "90802", "90803", "90804", "90805", "90806", "90807", "90808"],
    neighborhoods: ["Belmont Shore", "Naples", "Bixby Knolls", "Downtown Long Beach", "Alamitos Heights"],
    landmarks: ["Queen Mary", "Aquarium of the Pacific", "Long Beach Convention Center"],
    lat: 33.7701,
    lng: -118.1937,
  },
  {
    slug: "torrance",
    city: "Torrance",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["90501", "90502", "90503", "90504", "90505"],
    neighborhoods: ["Old Torrance", "Hollywood Riviera", "Seaside", "Walteria", "South Torrance"],
    landmarks: ["Del Amo Fashion Center", "Torrance Beach", "Madrona Marsh Preserve"],
    lat: 33.8358,
    lng: -118.3406,
  },
  {
    slug: "culver-city",
    city: "Culver City",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["90230", "90231", "90232"],
    neighborhoods: ["Downtown Culver City", "Culver Crest", "Blair Hills", "Fox Hills"],
    landmarks: ["Sony Pictures Studios", "Culver City Arts District", "Baldwin Hills"],
    lat: 34.0211,
    lng: -118.3965,
  },
  {
    slug: "inglewood",
    city: "Inglewood",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["90301", "90302", "90303", "90304", "90305"],
    neighborhoods: ["Downtown Inglewood", "Morningside Park", "Centinela Heights"],
    landmarks: ["SoFi Stadium", "The Forum", "Hollywood Park"],
    lat: 33.9617,
    lng: -118.3531,
  },
  {
    slug: "downey",
    city: "Downey",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["90239", "90240", "90241", "90242"],
    neighborhoods: ["Downtown Downey", "North Downey", "South Downey"],
    landmarks: ["Downey Landing", "Columbia Memorial Space Center", "Stonewood Center"],
    lat: 33.9401,
    lng: -118.1332,
  },
  {
    slug: "whittier",
    city: "Whittier",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["90601", "90602", "90603", "90604", "90605", "90606"],
    neighborhoods: ["Uptown Whittier", "East Whittier", "South Whittier", "Whittier Heights"],
    landmarks: ["Whittier Narrows", "Pio Pico State Historic Park", "Uptown Whittier"],
    lat: 33.9792,
    lng: -118.0328,
  },
  {
    slug: "pomona",
    city: "Pomona",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["91766", "91767", "91768"],
    neighborhoods: ["Downtown Pomona", "Phillips Ranch", "Indian Hill"],
    landmarks: ["Fairplex", "Cal Poly Pomona", "Pomona Arts Colony"],
    lat: 34.0551,
    lng: -117.7500,
  },
  {
    slug: "west-covina",
    city: "West Covina",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["91790", "91791", "91792"],
    neighborhoods: ["South Hills", "Cameron Park", "Cortez Park"],
    landmarks: ["Westfield West Covina", "Galster Wilderness Park"],
    lat: 34.0686,
    lng: -117.9390,
  },
  {
    slug: "alhambra",
    city: "Alhambra",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["91801", "91803"],
    neighborhoods: ["Downtown Alhambra", "Emery Park", "Midwick Tract", "Granada Park"],
    landmarks: ["Main Street Alhambra", "Almansor Park", "Alhambra Golf Course"],
    lat: 34.0953,
    lng: -118.1270,
  },
  {
    slug: "el-monte",
    city: "El Monte",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["91731", "91732", "91734"],
    neighborhoods: ["Downtown El Monte", "South El Monte", "Mountain View"],
    landmarks: ["El Monte Bus Station", "Whittier Narrows Recreation Area"],
    lat: 34.0686,
    lng: -118.0276,
  },
  {
    slug: "norwalk",
    city: "Norwalk",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["90650", "90651"],
    neighborhoods: ["North Norwalk", "South Norwalk", "Southeast Norwalk"],
    landmarks: ["Norwalk Town Square", "Cerritos College", "Hargitt House Museum"],
    lat: 33.9022,
    lng: -118.0817,
  },
  {
    slug: "compton",
    city: "Compton",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["90220", "90221", "90222"],
    neighborhoods: ["Downtown Compton", "Richland Farms", "Sunny Cove"],
    landmarks: ["Compton Creek", "Martin Luther King Jr. Transit Center"],
    lat: 33.8959,
    lng: -118.2201,
  },
  {
    slug: "hawthorne",
    city: "Hawthorne",
    state: "California",
    stateAbbr: "CA",
    county: "Los Angeles County",
    zipCodes: ["90250", "90251"],
    neighborhoods: ["Downtown Hawthorne", "North Hawthorne", "Holly Glen"],
    landmarks: ["SpaceX Headquarters", "The Beach Boys' childhood home", "Hawthorne Mall site"],
    lat: 33.9164,
    lng: -118.3526,
  },
]

export function getAreaBySlug(slug: string): SpotlessArea | undefined {
  return SPOTLESS_AREAS.find((a) => a.slug === slug)
}

export function getAllAreaSlugs(): string[] {
  return SPOTLESS_AREAS.map((a) => a.slug)
}

export function getAllCityNames(): string[] {
  return SPOTLESS_AREAS.map((a) => a.city)
}

// Business info used across the site
export const SPOTLESS_BUSINESS = {
  name: "Spotless Scrubbers",
  legalName: "Spotless Scrubbers LLC",
  phone: "(424) 677-1146",
  phoneRaw: "+14246771146",
  email: "spotlessscrubberscleaning@gmail.com",
  url: "https://spotlessscrubbers.org",
  foundingYear: 2023,
  areaServed: "Los Angeles County, CA",
  description:
<<<<<<< HEAD
    "Professional house cleaning in Los Angeles County. Instant booking, insured team, 100% satisfaction guaranteed.",
=======
    "Top-rated house cleaning service in Los Angeles County. Insured cleaners, satisfaction guaranteed.",
>>>>>>> Test
  rating: 5.0,
  reviewCount: 29,
  priceRange: "$$",
  address: {
    city: "Los Angeles",
    state: "California",
    stateAbbr: "CA",
    country: "US",
  },
  social: {
    instagram: "https://instagram.com/spotlessscrubbers",
    facebook: "https://facebook.com/spotlessscrubbers",
    yelp: "https://yelp.com/biz/spotless-scrubbers-los-angeles",
    google: "https://g.page/spotless-scrubbers",
  },
}
